WebshopLayer/Controllers/CrudController.cs
using AutoMapper;
using BusinessLogic;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web.Mvc;
using WebshopLayer.Classes;
using WebshopLayer.Models;
using HashLib;
using System.IO;
using System.Net.Mail;
using System.Net;
using System.Configuration;

namespace WebshopLayer.Controllers
{
    public class CrudController : Controller
    {
        // GET: Crud

        IMapper mapper;
        ILogic logic;
        CrudModel model;

        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            mapper = DTO.AutoMapperConfig.GetMapper();
            logic = new RealLogic();
            model = new CrudModel();
            model.ProductModel = new ProductModel();
            model.LoginModel = new LoginModel();
            model.AddObject = new CustomerModel();
            model.ContactModel = new ContactModel();

            var newestproducts = logic.GetNewestProducts();
            model.NewestProducts = mapper.Map<IQueryable<BusinessLogic.Queries.ProductsLowPrice>, List<Models.ProductModel>>(newestproducts);

            var offproducts = logic.GetTwoGames();
            model.OffProducts = mapper.Map<IQueryable<BusinessLogic.Queries.ProductsLowPrice>, List<Models.ProductModel>>(offproducts);

            var bestproducts = logic.GetThreeGames();
            model.BestProducts = mapper.Map<IQueryable<BusinessLogic.Queries.ProductsLowPrice>, List<Models.ProductModel>>(bestproducts);

            var categorylist = logic.GetCategroies();
            model.CategoryList = mapper.Map<IQueryable<Data.Categories>, List<Models.CategoryModel>>(categorylist);

            var productlist = logic.GetProducts();
            model.ProductList = mapper.Map<IQueryable<Data.Products>, List<Models.ProductModel>>(productlist);

            var customerlist = logic.GetCustomers();
            model.CustomerList = mapper.Map<IQueryable<Data.Customers>, List<Models.CustomerModel>>(customerlist);

            var platformlist = logic.GetPlatforms();
            model.PlatformList = mapper.Map<IQueryable<Data.Platforms>, List<Models.PlatformModel>>(platformlist);

            var wishlistgames = logic.WishList();
            model.WishListGames = mapper.Map<IQueryable<BusinessLogic.Queries.GetWishlistGame>, List<Models.GetWishListGameModel>>(wishlistgames);

            var orders = logic.Order();
            model.Order = mapper.Map<IQueryable<BusinessLogic.Queries.GetOrdersAndCustomersAndProducts>, List<Models.GetOrdersAndCustomersAndProductsModel>>(orders);

            base.OnActionExecuting(filterContext);
        }
        private CustomerModel getCustomerModel(int id)
        {
            Data.Customers c = logic.GetOneCustomer(id);
            return mapper.Map<Data.Customers, Models.CustomerModel>(c);
        }

        private ProductModel getProductModel(int id)
        {
            Data.Products p = logic.GetOneProduct(id);
            return mapper.Map<Data.Products, Models.ProductModel>(p);
        }

        private List<ProductModel> getProducts(int id)
        {
            var p = logic.ProductsInPlatform(id);
            return mapper.Map<IQueryable<BusinessLogic.Queries.ProductsInPlatform>, List<Models.ProductModel>>(p);
        }
        private List<ProductModel> getProductsPriceLow()
        {
            var p = logic.ProductsLowPrice();
            return mapper.Map<IQueryable<BusinessLogic.Queries.ProductsLowPrice>, List<Models.ProductModel>>(p);
        }
        private List<ProductModel> getProductsPriceHigh()
        {
            var p = logic.ProductsHighPrice();
            return mapper.Map<IQueryable<BusinessLogic.Queries.ProductsHighPrice>, List<Models.ProductModel>>(p);
        }

        private List<ProductModel> searchProduct(string search)
        {
            var p = logic.GetProductsAndPlatformsAndCategories(search);
            return mapper.Map<IQueryable<BusinessLogic.Queries.GetProductsAndPlatformsAndCategories>, List<Models.ProductModel>>(p);
        }

        // Menüpontok, belépés nélkül elérhető
        public ActionResult Index()
        {
            ViewData["TargetAction"] = "AddToWishList";
            ViewData["TargetAction"] = "AddToCart";
            return View("CrudIndex", model);
        }

        public ActionResult Contact()
        {
            return View("CrudContact");
        }

        public ActionResult PlatformList(int id)
        {
            if (id == 100)
            {
                return View("CrudIndex", model);
            }
            model.ProductList = getProducts(id);
            return View("CrudIndex", model);
        }

        public ActionResult Details(int id)
        {
            ViewData["TargetAction"] = "AddToWishList";
            return View("CrudProductDetails", getProductModel(id));
        }

        public ActionResult Reg()
        {
            ViewData["TargetAction"] = "AddNew";
            return View("_CrudRegisterPartial", model);
        }
        public ActionResult LoginView()
        {
            return View("CrudLogin");
        }

        public ActionResult Show(int id)
        {
            var productlist = logic.GetProducts();
            foreach (var item in productlist)
            {
                if (id == item.ID)
                {
                    var imageData = item.image1;
                    return File(imageData, "image/jpg");
                }
            }
            return View("LoginErrorView");
        }

        public ActionResult PriceType(int id)
        {
            if (id == 1)
            {
                model.ProductList = getProductsPriceLow();
                return View("CrudIndex", model);
            }
            model.ProductList = getProductsPriceHigh();
            return View("CrudIndex", model);
        }

        public ActionResult Search(string search)
        {
            model.ProductList = searchProduct(search);
            return View("CrudIndex", model);
        }

        public ActionResult SendEmail(ContactModel model)
        {
            //Dictionary<string, FileStream> attachments = xxx;
            string targetAddr = "dicehtc@gmail.com";
            string senderAddr = model.E_mail;
            string subject = model.FullName;
            string body = model.Message;

            MailMessage mm = new MailMessage(senderAddr, targetAddr, subject, body);
            mm.SubjectEncoding = UTF8Encoding.UTF8;
            mm.BodyEncoding = UTF8Encoding.UTF8;
            mm.DeliveryNotificationOptions = DeliveryNotificationOptions.OnFailure;
            //if (attachments != null)
            //{
            //    foreach (var akt in attachments)
            //    {
            //        mm.Attachments.Add(new Attachment(akt.Value, akt.Key));
            //    }
            //}
            ServicePointManager.ServerCertificateValidationCallback =
                    (sender, certificate, chain, sslPolicyErrors) => true;
            SmtpClient client = new SmtpClient();
            client.Port = 587;
            client.Host = "smtp.gmail.com";
            client.EnableSsl = true;
            client.Timeout = 100000;
            client.DeliveryMethod = SmtpDeliveryMethod.Network;
            client.UseDefaultCredentials = false;
            //string password = Crypto.DecryptStringAES(ConfigurationManager.AppSettings["SMTP_PASS"], Services.ComputerId);
            //client.Credentials = new System.Net.NetworkCredential(ConfigurationManager.AppSettings["SMTP_USER"], password);
            client.Credentials = new NetworkCredential("dicehtc@gmail.com", "jelszo");
            client.Send(mm);
            return View("CrudIndex");
        }

        // Belépés után elérhető
        // Rendelés
        [MyAuthorizeFilter]
        public ActionResult Cart()
        {
            return View("CrudCart", MyAuthorizeFilterAttribute.SessionStore);
        }

        [MyAuthorizeFilter]
        public ActionResult UpdateCartItem(FormCollection fc)
        {
            string[] quantities = fc.GetValues("quantity");
            var list = MyAuthorizeFilterAttribute.SessionStore;
            for (int i = 0; i < list.Count; i++)
            {
                list[i].Quantity = Convert.ToInt32(quantities[i]);
            }
                Session["Cart"] = list;
                return RedirectToAction("Cart");
            
        }

        [MyAuthorizeFilter]
        public ActionResult RemoveCartItem(int id)
        {
            var list = MyAuthorizeFilterAttribute.SessionStore;
            try
            {
                list.Remove(id);
            }
            catch (ArgumentException)
            {
                return View("LoginErrorView");
            }           
            return RedirectToAction("Cart");
        }

        [MyAuthorizeFilter]
        public ActionResult AddToCart(int customerid, int productid, string productname, string description, int price)
        {
            var listmodel = MyAuthorizeFilterAttribute.SessionStore;
            GetOrdersAndCustomersAndProductsModel Cart = new GetOrdersAndCustomersAndProductsModel();
            int id=0;           
            Cart.CustomerID = customerid;
            Cart.ProductID = productid;
            Cart.ProductName = productname;
            Cart.Description = description;
            Cart.Price = price;                     
            Cart.OrderID++;
            Cart.Quantity = 1;
            Cart.SubTotal = Cart.Quantity * price;
            if (listmodel != null)
            {
                foreach (var item in listmodel)
                {
                    id++;
                    
                    if (Cart.CustomerID == item.Value.CustomerID && Cart.ProductID == item.Value.ProductID)
                    {
                        return View("LoginErrorView");
                    }
                }               
            }

WebshopLayer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head runat="server">
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>GAMERz Webshop</title>
    <!-- Bootstrap core CSS -->
    <link href="~/assets/css/bootstrap.css" rel="stylesheet" />
    <!-- Fontawesome core CSS -->
    <link href="~/assets/css/font-awesome.min.css" rel="stylesheet" />
    <!--GOOGLE FONT -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />
    <!--Slide Show Css -->
    <link href="~/assets/ItemSlider/css/main-style.css" rel="stylesheet" />
    <!-- custom CSS here -->
    <link href="~/assets/css/style.css" rel="stylesheet" />
    @Styles.Render("~/assets/css")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/ItemSlider")
    @Scripts.Render("~/bundles/jquery")

    @Html.AntiForgeryToken()
    <form id="form1" runat="server">
        <nav class="navbar navbar-default" role="navigation">
            <div class="container-fluid row">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("GAMERz Webshop", "Index", "Crud", new {@class="navbar-brand" })
                    @*<a class="navbar-brand"><strong>GAMERz</strong> Webshop</a>*@

                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav navbar-right">
                        <li>@Html.ActionLink("Főoldal", "Index", "Crud")</li>
                        <li>@Html.ActionLink("Kapcsolat", "Contact", "Crud")</li>
                        @if (Session["UserId"] != null) 
                        {
                            @Html.AntiForgeryToken()
                            <li>@Html.ActionLink("Kosár", "Cart", "Crud")</li>
                            <li>@Html.ActionLink("Kivánságlista", "Wishlist", "Crud")</li>

                                <li>@Html.ActionLink("Kilépés", "Logout", "Crud")</li>
                                <li>
                                    <a class="navbar-brand">@Html.ActionLink("Hello " + Session["UserEmail"] + "!", "Profil", new { id = Session["UserId"] })</a>
                                </li>
                        }
                        else
                        {
                            
                            <li>@Html.ActionLink("Regisztráció", "Reg", "Crud")</li>
                            <li>@Html.ActionLink("Belépés", "LoginView", "Crud")</li>

                        }
                    </ul>
                </div>
                <!-- /.navbar-collapse -->
            </div>
            <!-- /.container-fluid -->
        </nav>
    </form>
</head>
<body>
    @RenderBody()



    <!-- /.container -->
    <!--Footer -->
    <div class="col-md-12 footer-box">




        <div class="row">
            <div class="col-md-4">
                <strong>Irodánk:</strong>
                <hr />
                <p>
                    1115, Bartók Béla út 125H,<br />
                    Budapest, Magyarország<br />
                    Telefon: +36 1 365 3003<br />
                    Email: info@gamerzwebshop.com<br />
                </p>

                2017 | www.gamerzwebshop.azurewebsites.net | All Right Reserved
            </div>
            <div class="col-md-4 social-box">
                <strong>Online elérhetőségeink: </strong>
                <hr />
                <a href="#"><i class="fa fa-facebook-square fa-3x "></i></a>
                <a href="#"><i class="fa fa-twitter-square fa-3x "></i></a>
                <a href="#"><i class="fa fa-google-plus-square fa-3x c"></i></a>
                <a href="#"><i class="fa fa-linkedin-square fa-3x "></i></a>
                <a href="#"><i class="fa fa-pinterest-square fa-3x "></i></a>
                
            </div>
        </div>
        <hr />
    </div>
    <!-- /.col -->
    <div class="col-md-12 end-box ">
        &copy; 2017 | &nbsp; Email: info@gamerzwebshop.com
    </div>
    <!-- /.col -->
    <!--Footer end -->
    @section Scripts{
    <!--Core JavaScript file  -->
    <script src="~/assets/js/jquery-1.10.2.js"></script>
    <!--bootstrap JavaScript file  -->
    <script src="~/assets/js/bootstrap.js"></script>
        }


    @Styles.Render("~/assets/css")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/ItemSlider")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @RenderSection("scripts", required: false)
</body>
</html>